language: julia
os:
  - linux
  - osx
julia:
  - 0.5
#  - nightly
#  - release
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MIToS"); Pkg.test("MIToS"; coverage=true)'
after_success:
  - ./.travis_after_success.sh
